import React,{useEffect,useRef} from 'react';
import {ActivityIndicator,Animated,Easing,Pressable,StyleSheet,Text,TextInput,View,ViewStyle} from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import {LinearGradient} from 'expo-linear-gradient';
import {C,shadow} from '../lib/theme';
export function Ball({size=34}:{size?:number}){return <View style={{width:size,height:size,borderRadius:size/2,backgroundColor:C.red,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:'#F48680',transform:[{rotate:'-28deg'}],overflow:'hidden'}}><View style={{width:size*1.3,height:size*.35,borderTopWidth:1.5,borderBottomWidth:1.5,borderColor:'#FBCBC4',borderRadius:size/2,transform:[{rotate:'35deg'}]}}/></View>}
export function Label({children,style}:{children:React.ReactNode;style?:any}){return <Text style={[{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:C.green2,textTransform:'uppercase'},style]}>{children}</Text>}
export function Heading({children,right}:{children:React.ReactNode;right?:React.ReactNode}){return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14}}><Text style={{fontSize:22,fontWeight:'900',color:C.ink,letterSpacing:-.7}}>{children}</Text>{right}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[{backgroundColor:C.paper,borderRadius:22,padding:19,...shadow},style]}>{children}</View>}
export function IconCircle({name,color=C.green,bg=C.mint,size=42}:{name:any;color?:string;bg?:string;size?:number}){return <View style={{width:size,height:size,borderRadius:size/2,backgroundColor:bg,alignItems:'center',justifyContent:'center'}}><Ionicons name={name} size={size*.47} color={color}/></View>}
export function Button({title,onPress,variant='primary',icon,disabled=false,small=false}:{title:string;onPress:()=>void;variant?:'primary'|'outline'|'light'|'danger';icon?:any;disabled?:boolean;small?:boolean}){const bg=variant==='primary'?C.green:variant==='light'?C.mint:variant==='danger'?C.softRed:'transparent';const fg=variant==='primary'?'white':variant==='danger'?C.red:C.green;return <Pressable onPress={onPress} disabled={disabled} style={({pressed})=>[{backgroundColor:bg,borderWidth:variant==='outline'?1:0,borderColor:C.line,borderRadius:14,paddingHorizontal:small?14:20,height:small?38:49,opacity:disabled?.45:pressed?.78:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8}]}>{icon&&<Ionicons name={icon} size={17} color={fg}/>}<Text style={{color:fg,fontSize:small?12:14,fontWeight:'800'}}>{title}</Text></Pressable>}
export function Field({label,value,onChangeText,placeholder,multiline,keyboardType,secureTextEntry}:{label:string;value:string;onChangeText:(t:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:any;secureTextEntry?:boolean}){return <View style={{marginBottom:15}}><Text style={{fontSize:12,color:C.gray,fontWeight:'700',marginBottom:8}}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor='#9BAC9E' multiline={multiline} keyboardType={keyboardType} secureTextEntry={secureTextEntry} autoCapitalize={keyboardType==='email-address'?'none':'sentences'} style={{borderRadius:14,backgroundColor:'#F5F8F3',borderWidth:1,borderColor:C.line,color:C.ink,fontSize:15,paddingHorizontal:15,paddingVertical:12,minHeight:multiline?90:49,textAlignVertical:multiline?'top':'center'}}/></View>}
export function Divider(){return <View style={{height:1,backgroundColor:C.line,marginVertical:15}}/>}
export function Empty({icon,title,subtitle}:{icon:any;title:string;subtitle:string}){return <View style={{alignItems:'center',paddingVertical:25,paddingHorizontal:20}}><IconCircle name={icon} size={56}/><Text style={{fontSize:16,fontWeight:'800',color:C.ink,marginTop:13}}>{title}</Text><Text style={{fontSize:13,color:C.gray,textAlign:'center',lineHeight:20,marginTop:5}}>{subtitle}</Text></View>}
export function Loader(){const turn=useRef(new Animated.Value(0)).current;useEffect(()=>{const loop=Animated.loop(Animated.timing(turn,{toValue:1,duration:1600,easing:Easing.linear,useNativeDriver:true}));loop.start();return()=>loop.stop()},[]);return <View style={{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'}}><Animated.View style={{transform:[{rotate:turn.interpolate({inputRange:[0,1],outputRange:['0deg','360deg']})}]}}><Ball size={64}/></Animated.View><Text style={{fontSize:23,fontWeight:'900',color:C.green,marginTop:23}}>Airport Cricket Team</Text><Text style={{fontSize:13,color:C.gray,marginTop:5}}>Play Together Every Morning</Text><ActivityIndicator color={C.red} style={{marginTop:22}}/></View>}
export function ScreenTop({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle?:string}){return <View style={{paddingHorizontal:22,paddingTop:16,paddingBottom:23}}><Label>{eyebrow}</Label><Text style={{fontSize:31,fontWeight:'900',color:C.ink,letterSpacing:-1.2,marginTop:5}}>{title}</Text>{subtitle&&<Text style={{fontSize:13,color:C.gray,marginTop:5}}>{subtitle}</Text>}</View>}
export function DarkBanner({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <LinearGradient colors={[C.deep,C.green2]} start={{x:0,y:0}} end={{x:1,y:1}} style={[{borderRadius:23,padding:21,overflow:'hidden'},style]}>{children}</LinearGradient>}
export const common=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},body:{paddingHorizontal:20,paddingBottom:110},row:{flexDirection:'row',alignItems:'center'},muted:{color:C.gray,fontSize:13,lineHeight:19},sectionGap:{height:25}});
