import React,{useEffect,useRef,useState} from 'react';import {ActivityIndicator,Alert,FlatList,Pressable,SafeAreaView,Text,View} from 'react-native';import Ionicons from '@expo/vector-icons/Ionicons';import {Image} from 'expo-image';import {useVideoPlayer,VideoView} from 'expo-video';import {useEvent} from 'expo';import {useIsFocused} from '@react-navigation/native';import {BEST_SHOT_CLIP_SECONDS} from '../lib/config';import {useApp} from '../lib/AppContext';import {C} from '../lib/theme';import {hasBirthdayToday,localDay,prettyDate} from '../lib/types';import {Ball,Button,Card,common,DarkBanner,Divider,Empty,Heading,IconCircle,Label} from '../components/UI';
export default function HomeScreen({navigation}:any){const lastBallTap=useRef(0);const {user,online,adminAuthorized,data,togglePresence,toggleVote,showAuth}=useApp();const today=localDay(),tomorrow=localDay(1),bookedToday=data.bookings.filter(b=>b.date===today).length,bookedTomorrow=data.bookings.filter(b=>b.date===tomorrow).length,present=data.presences.filter(p=>p.date===today),myPresence=present.some(p=>p.userId===user?.id),latest=[...data.notices].sort((a,b)=>b.createdAt-a.createdAt)[0];const run=async(fn:()=>Promise<void>)=>{if(!user){showAuth();return}try{await fn()}catch(e:any){Alert.alert('Heads up',e.message)}};const items=['hero','offline','birthday','application','requests','notice','session','stats','tea','shot','special','explore'];return <SafeAreaView style={common.screen}><FlatList data={items} keyExtractor={x=>x} contentContainerStyle={{paddingHorizontal:20,paddingBottom:115}} showsVerticalScrollIndicator={false} renderItem={({item})=>{switch(item){case 'hero':return <View style={{paddingTop:19,paddingBottom:23,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View><Label>YOUR MORNING STARTS HERE</Label><Text style={{fontSize:29,fontWeight:'900',color:C.ink,letterSpacing:-1.2,marginTop:5}}>Airport Cricket<Text style={{color:C.red}}>.</Text></Text><Text style={{fontSize:13,color:C.gray,marginTop:3}}>Play Together Every Morning</Text></View><Pressable onPress={()=>{const now=Date.now();if(now-lastBallTap.current<450){lastBallTap.current=0;navigation.navigate('Admin')}else lastBallTap.current=now}} onLongPress={()=>navigation.navigate('Admin')} accessibilityRole='button' accessibilityLabel='Admin panel' accessibilityHint='Double tap the cricket ball or press and hold to open the admin panel' hitSlop={12} style={{padding:3}}><Ball size={43}/></Pressable></View>;
case 'offline':return online?null:<View style={{marginBottom:17,backgroundColor:'#FDECEC',borderWidth:1,borderColor:'#F4C7C7',borderRadius:18,padding:16,flexDirection:'row',gap:12,alignItems:'center'}}><IconCircle name='cloud-offline-outline' bg='#F9D2D2' color={C.red} size={39}/><View style={{flex:1}}><Text style={{fontSize:14,color:C.ink,fontWeight:'900'}}>Not connected to the team</Text><Text style={{fontSize:12,color:C.gray,marginTop:4,lineHeight:18}}>This build has no Firebase keys, so everything stays on this phone only. Rebuild the app with the Firebase keys to share data with the team.</Text></View></View>;
case 'requests':{const pending=data.players.filter(p=>p.approvalStatus==='pending').length;return adminAuthorized&&pending?<Pressable onPress={()=>navigation.navigate('Admin')} style={{marginBottom:17}}><View style={{backgroundColor:'#E8F1FF',borderWidth:1,borderColor:'#C9DCF7',borderRadius:18,padding:16,flexDirection:'row',gap:12,alignItems:'center'}}><IconCircle name='person-add-outline' bg='#CFE1FA' color='#245EA8' size={39}/><View style={{flex:1}}><Text style={{fontSize:14,color:C.ink,fontWeight:'900'}}>{pending} new player{pending>1?'s':''} waiting</Text><Text style={{fontSize:12,color:C.gray,marginTop:4}}>Tap to review and approve.</Text></View><Ionicons name='arrow-forward' size={17} color='#245EA8'/></View></Pressable>:null}
case 'birthday':{const celebrants=data.players.filter(p=>hasBirthdayToday(p.dateOfBirth));if(user&&hasBirthdayToday(user.dateOfBirth)&&!celebrants.some(p=>p.id===user.id))celebrants.unshift(user);return celebrants.length?<View style={{marginBottom:17,backgroundColor:'#FFF0EA',borderColor:'#F6D6C8',borderWidth:1,borderRadius:19,padding:17,flexDirection:'row',alignItems:'center',gap:12}}><IconCircle name='gift-outline' bg='#FAD9D0' color={C.red} size={42}/><View style={{flex:1}}><Label style={{color:C.red}}>BIRTHDAY ON THE TEAM</Label><Text style={{color:C.ink,fontSize:15,fontWeight:'900',marginTop:4}}>{celebrants.some(p=>p.id===user?.id)?`Happy birthday, ${user?.name}! 🎉`:`Happy birthday, ${celebrants.map(p=>p.name).join(' & ')}! 🎉`}</Text><Text style={{fontSize:12,color:C.gray,marginTop:3}}>Wishing you a day full of runs and smiles.</Text></View></View>:null}
case 'application':return user?.approvalStatus==='pending'?<View style={{marginBottom:17,backgroundColor:'#FFF3E4',borderWidth:1,borderColor:'#F6DEBE',borderRadius:18,padding:16,flexDirection:'row',gap:12,alignItems:'center'}}><IconCircle name='time-outline' bg='#FFE5C2' color='#A86C2C' size={39}/><View style={{flex:1}}><Text style={{fontSize:14,color:C.ink,fontWeight:'900'}}>Your application is pending</Text><Text style={{fontSize:12,color:C.gray,marginTop:4,lineHeight:18}}>An admin will review your profile. You can book and join teams once approved.</Text></View></View>:null;
case 'notice':return <Pressable onPress={()=>adminAuthorized?navigation.navigate('Admin'):null} style={{marginBottom:22}}><View style={{backgroundColor:C.lime,borderRadius:19,padding:16,flexDirection:'row',gap:12,alignItems:'flex-start'}}><IconCircle name='megaphone-outline' bg='#BDD778' color={C.deep} size={38}/><View style={{flex:1}}><Text style={{fontSize:11,fontWeight:'900',color:C.green,letterSpacing:1}}>TEAM NOTICE</Text><Text style={{fontSize:15,fontWeight:'900',color:C.ink,marginTop:4}}>{latest?.title||'Stay in the loop'}</Text><Text style={{fontSize:12,color:C.deep,marginTop:3,lineHeight:18}}>{latest?.body||'Team updates and announcements will appear here. Ready for a good game?'}</Text></View><Ionicons name='arrow-forward' size={17} color={C.green}/></View></Pressable>;
case 'session':return <View style={{marginBottom:23}}><DarkBanner><View style={{flexDirection:'row',justifyContent:'space-between'}}><View><Text style={{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:C.lime}}>THE DAILY SESSION</Text><Text style={{fontSize:25,fontWeight:'900',color:'white',marginTop:8,letterSpacing:-.8}}>{data.settings.sessionLabel}</Text><Text style={{fontSize:13,color:'#D2E3D7',marginTop:5}}>{data.settings.matchType}</Text></View><Ionicons name='sunny-outline' color={C.lime} size={36}/></View><View style={{height:1,backgroundColor:'#FFFFFF24',marginVertical:18}}/><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Ionicons name='time-outline' color={C.lime} size={20}/><Text style={{color:'white',fontWeight:'800',fontSize:15}}>6:00 – 8:30 AM</Text></View><Text style={{color:'#BCD6C1',fontSize:12}}>{prettyDate(today)}</Text></View>{(data.settings.overs||data.settings.ballInfo||data.settings.practiceMatch)?<Text style={{color:'#D2E3D7',fontSize:12,marginTop:12}}>{[data.settings.practiceMatch,data.settings.overs&&`${data.settings.overs} overs`,data.settings.ballInfo].filter(Boolean).join('  ·  ')}</Text>:null}</DarkBanner></View>;
case 'stats':return <View style={{marginBottom:24}}><Heading right={<Pressable onPress={()=>navigation.navigate('Booking')}><Text style={{color:C.green,fontWeight:'800',fontSize:12}}>VIEW BOOKING  →</Text></Pressable>}>On the pitch</Heading><View style={{flexDirection:'row',gap:11}}>{[[today,'TODAY',bookedToday],[tomorrow,'TOMORROW',bookedTomorrow]].map(([date,label,count]:any)=><Pressable key={date} onPress={()=>navigation.navigate('Booking')} style={{flex:1,backgroundColor:'white',borderRadius:20,padding:17,borderWidth:1,borderColor:C.line}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Label>{label}</Label><Ionicons name='arrow-forward-outline' color={C.gray} size={17}/></View><Text style={{fontSize:30,fontWeight:'900',color:C.ink,marginTop:12}}>{count}<Text style={{fontSize:15,color:C.gray}}>/{data.settings.maxSlots}</Text></Text><Text style={{fontSize:12,color:C.gray,marginTop:2}}>{data.settings.maxSlots-count>0?`${data.settings.maxSlots-count} spots open`:'Slots are full'}</Text><View style={{height:4,backgroundColor:C.mint,borderRadius:4,marginTop:14,overflow:'hidden'}}><View style={{width:`${Math.min(100,count/data.settings.maxSlots*100)}%`,height:4,backgroundColor:C.green}}/></View></Pressable>)}</View></View>;
case 'tea':return <View style={{marginBottom:24}}><Heading right={<View style={{paddingHorizontal:10,paddingVertical:5,backgroundColor:C.mint,borderRadius:99}}><Text style={{fontSize:11,fontWeight:'800',color:C.green}}>{present.length} HERE</Text></View>}>Cha er Dokane ☕</Heading><Card><View style={{flexDirection:'row',alignItems:'center',gap:13}}><IconCircle name='cafe-outline' bg='#F9F1E3' color='#AC7736' size={46}/><View style={{flex:1}}><Text style={{fontSize:15,fontWeight:'800',color:C.ink}}>Who's at the tea stall?</Text><Text style={{fontSize:12,color:C.gray,marginTop:3}}>The morning hangout · resets daily</Text></View></View>{present.length?<View style={{marginTop:15}}>{present.map(p=>{const count=data.votes.filter(v=>v.date===today&&v.targetId===p.userId).length;return <View key={p.id} style={{flexDirection:'row',alignItems:'center',paddingVertical:8,gap:9}}><View style={{width:29,height:29,borderRadius:15,backgroundColor:C.mint,alignItems:'center',justifyContent:'center'}}><Text style={{fontWeight:'900',color:C.green}}>{p.name[0]}</Text></View><Text style={{flex:1,fontSize:13,color:C.ink,fontWeight:'700'}}>{p.name}</Text><Pressable disabled={!user||user.id===p.userId} onPress={()=>run(()=>toggleVote(today,p.userId))} style={{backgroundColor:C.bg,paddingHorizontal:10,paddingVertical:7,borderRadius:10}}><Text style={{fontSize:11,color:C.green,fontWeight:'800'}}><Ionicons name='checkmark-circle-outline' size={13}/> {count} checked</Text></Pressable></View>})}</View>:<Text style={{fontSize:12,color:C.gray,marginTop:15}}>No one has checked in yet. Be the first to say hello.</Text>}<View style={{marginTop:16}}><Button title={myPresence?'Leave tea stall':'I’m at the tea stall'} onPress={()=>run(()=>togglePresence(today))} disabled={user?.approvalStatus==='pending'} variant={myPresence?'outline':'primary'} icon={myPresence?'exit-outline':'location-outline'}/></View></Card></View>;
case 'shot':return <View style={{marginBottom:24}}><Heading>Best shot</Heading><Card style={{padding:0,overflow:'hidden'}}>{data.settings.bestShotUrl?<BestShotVideo key={data.settings.bestShotUrl} uri={data.settings.bestShotUrl}/>:data.settings.bestShotImage?<Image source={{uri:data.settings.bestShotImage}} style={{height:150,width:'100%'}} contentFit='cover'/>:<View style={{height:132,backgroundColor:'#E9F1DF',alignItems:'center',justifyContent:'center'}}><View style={{width:105,height:105,borderWidth:2,borderColor:'#CADDBE',borderRadius:60,position:'absolute',right:26,top:13}}/><Ionicons name='videocam-outline' size={38} color={C.green}/></View>}<View style={{padding:17}}><Text style={{fontSize:15,fontWeight:'900',color:C.ink}}>{data.settings.bestShotTitle||'A moment worth replaying'}</Text><Text style={{fontSize:12,color:C.gray,marginTop:3}}>{data.settings.bestShotUrl?'Plays on a loop · tap the speaker for sound':'The next great shot could be yours.'}</Text></View></Card></View>;
case 'special':return data.settings.specialMatch?<View style={{marginBottom:24}}><Card style={{backgroundColor:'#FDF4EC',borderWidth:1,borderColor:'#F6E4D4'}}><Label style={{color:'#B77938'}}>UPCOMING SPECIAL MATCH</Label><Text style={{fontSize:18,fontWeight:'900',color:C.ink,marginTop:7}}>{data.settings.specialMatch}</Text><Text style={{fontSize:13,color:C.gray,marginTop:4}}>{data.settings.specialTime||'Details coming soon'}</Text></Card></View>:null;
case 'explore':return <View><Heading>Explore the club</Heading><View style={{flexDirection:'row',gap:11}}>{[['Teams','people-outline'],['Charity','heart-outline']].map(([title,icon]:any)=><Pressable key={title} onPress={()=>navigation.navigate(title)} style={{flex:1,backgroundColor:C.paper,borderRadius:18,padding:17,flexDirection:'row',alignItems:'center',gap:9,borderWidth:1,borderColor:C.line}}><Ionicons name={icon} size={19} color={C.green}/><Text style={{fontWeight:'800',color:C.ink,fontSize:13}}>{title}</Text><Ionicons name='arrow-forward' size={14} color={C.gray}/></Pressable>)}</View></View>;
default:return null}}}/></SafeAreaView>}

// Best-shot clip: plays inside the app, muted, on a loop (paused when you leave the Home tab).
// Admins can upload a video of ANY length. Re-encoding/cutting the file needs a
// native video-editing library, which is a much heavier, harder-to-verify addition
// (see AGENTS.md). Instead we play only the first BEST_SHOT_CLIP_SECONDS seconds
// on a loop -- same visible result (a short looping clip) with no extra native
// dependency and nothing that can fail to build.
function BestShotVideo({uri}:{uri:string}){
 const player=useVideoPlayer(uri,p=>{p.loop=true;p.muted=true;p.play()});
 const focused=useIsFocused();
 const [muted,setMuted]=useState(true);
 const [ready,setReady]=useState(false);
 useEffect(()=>{if(focused)player.play();else player.pause()},[focused,player]);
 useEffect(()=>{player.muted=muted},[muted,player]);
 useEffect(()=>{player.timeUpdateEventInterval=0.25},[player]);
 const timeUpdate=useEvent(player,'timeUpdate');
 useEffect(()=>{if(timeUpdate&&timeUpdate.currentTime>=BEST_SHOT_CLIP_SECONDS){player.currentTime=0;if(!player.playing)player.play()}},[timeUpdate,player]);
 const status=useEvent(player,'statusChange',{status:player.status});
 useEffect(()=>{if(status?.status==='readyToPlay')setReady(true)},[status]);
 return <View style={{height:210,width:'100%',backgroundColor:'#0B1F16'}}>{!ready&&<View style={{position:'absolute',inset:0,alignItems:'center',justifyContent:'center'}}><ActivityIndicator color='white'/></View>}<VideoView player={player} nativeControls={false} contentFit='cover' style={{width:'100%',height:'100%'}}/><Pressable onPress={()=>setMuted(m=>!m)} hitSlop={10} style={{position:'absolute',right:12,bottom:12,backgroundColor:'#00000088',borderRadius:18,padding:8}}><Ionicons name={muted?'volume-mute':'volume-high'} size={18} color='white'/></Pressable></View>
}
